using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using FluentORM.Core.Abstractions;
using FluentORM.Core.Mapping;
using FluentORM.Migrations.Drift;

namespace FluentORM.Migrations.Scaffold;

public sealed class ScaffoldGenerator
{
    private readonly SchemaDriftDetector _detector;
    private readonly EntityMapRegistry _registry;

    public ScaffoldGenerator(SchemaDriftDetector detector, EntityMapRegistry registry)
    {
        _detector = detector;
        _registry = registry;
    }

    public async Task<string> GenerateAsync(
        string description,
        string? outputFolder = null,
        bool dryRun = false,
        CancellationToken ct = default)
    {
        var report = await _detector.DetectAsync(ct);
        if (!report.Issues.Any()) return "-- No schema drift detected. No migration needed.";

        var version = GenerateVersion();
        var className = ToPascalCase(description);

        var content = GenerateMigrationFile(version, description, className, report);

        if (!dryRun && outputFolder != null)
        {
            var fileName = Path.Combine(outputFolder, $"Migration_{version}_{className}.cs");
            await File.WriteAllTextAsync(fileName, content, ct);
            return $"Generated: {fileName}";
        }

        return content;
    }

    private string GenerateMigrationFile(long version, string description, string className, DriftReport report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ╔══════════════════════════════════════════════════════════╗");
        sb.AppendLine("// ║  AUTO-GENERATED by FluentORM scaffold                   ║");
        sb.AppendLine($"// ║  Generated : {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC                    ║");
        sb.AppendLine($"// ║  Detected  : {report.Issues.Count} schema drift issue(s)                      ║");
        sb.AppendLine("// ║  REVIEW THIS FILE BEFORE COMMITTING                     ║");
        sb.AppendLine("// ╚══════════════════════════════════════════════════════════╝");
        sb.AppendLine();
        sb.AppendLine("using FluentORM.Core.Attributes;");
        sb.AppendLine("using FluentORM.Migrations.Engine;");
        sb.AppendLine("using FluentORM.Migrations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"[Migration({version}, \"{description}\")]");

        var hasDestructive = report.Issues.Any(i =>
            i.Message.Contains("DROP") || i.Message.Contains("permanently"));
        if (hasDestructive)
            sb.AppendLine($"[Destructive(\"Review generated migration — may contain destructive operations.\")]");

        sb.AppendLine($"public class {className} : Migration");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Up(SchemaBuilder schema)");
        sb.AppendLine("    {");

        foreach (var issue in report.Issues.Where(i => i.Severity == DriftSeverity.Error))
        {
            sb.AppendLine($"        // DRIFT DETECTED: {issue.Message.Replace("\n", "\n        // ")}");
            if (issue.SuggestedFix != null)
                sb.AppendLine($"        {issue.SuggestedFix}");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override void Down(SchemaBuilder schema)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement rollback");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static long GenerateVersion()
    {
        var now = DateTime.UtcNow;
        return long.Parse($"{now:yyyyMMdd}001");
    }

    private static string ToPascalCase(string s)
    {
        return string.Concat(s.Split('_', ' ', '-')
            .Select(w => w.Length > 0 ? char.ToUpper(w[0]) + w[1..] : ""));
    }
}
